# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.delete_all
Category.delete_all
Order.delete_all
Item.delete_all

user1 = User.create!(username: "KillaCam", password: "password", full_name: "Killa Cam", address: "123 here", state: "NY")
user2 = User.create!(username: "Admin", password: "adminpassword", role: 1, full_name: "Admin", address: "123 here", state: "CO")
user3 = User.create!(username: "Alex", password: "password", full_name: "Alex", address: "123 here", state: "CO")

category1 = Category.create!(name: "Jedi Padawan")
category2 = Category.create!(name: "Jedi Master")
category3 = Category.create!(name: "Sith Apprentice")
category4 = Category.create!(name: "Sith Lord")

item1 = Item.create!(name: "Obi-Wan Kenobi's Lightsaber", description: "Obi-Wan Kenobi's lightsaber was the third lightsaber that was constructed and wielded by Jedi Master Obi-Wan Kenobi during the Clone Wars after he lost his second one prior to the Battle of Geonosis. He would eventually use this lightsaber to duel his fallen apprentice Darth Vader on Mustafar, and would continue to wield the weapon during his 19-year exile on Tatooine up until his death at the hands of Vader during their rematch on the Death Star. Obi-Wan's second apprentice Luke Skywalker would later use this weapon's design as a basis for the construction of his second lightsaber.", price: 300.0, image: "https://vignette.wikia.nocookie.net/starwars/images/d/d5/KenobiEpIIISaber-MR.jpg/revision/latest?cb=20100618033432", status: "retired", category: category2, retired_count: 1)
item2 = Item.create!(name: "Exar Kun's Lightsaber", description: "The lightsaber of Jedi Knight Exar Kun was a device that was initially created to produce a single beam of blue-white energy. However, upon his ascension to Dark Lord of the Sith, Kun redesigned his lightsaber based on instructions hidden within an antiquated Sith holocron. The finished product was a double-bladed weapon imbued with dark side energy, from which sapphire blades materialized up to 1.5 meters from either end of the hilt.", price: 400.0, image: "https://vignette.wikia.nocookie.net/starwars/images/1/11/Kun%27s_Lightsaber.jpg/revision/latest?cb=20080814035831", status: "active", category: category4)
item3 = Item.create!(name: "Darth Maul's Lightsaber", description: "Maul used the saberstaff on countless missions for his master, Darth Sidious. With it he embarked on missions to kill Jedi and to eliminate enemies. Maul used the saberstaff to eliminate Jedi Anoon Bondara, Siolo Ur Manka, Qui-Gon Jinn and Darsha Assant. He used the lightsaber in his mission to cripple the Black Sun criminal syndicate.", image: "https://s3.envato.com/files/184762216/Preview%20Image%20Set/DMLS%202.jpg", price: 250.0, category: category3, status: "active")
item4 = Item.create!(name: "Mace Windu's Lightsaber", description: "One of the most distinctive lightsabers in the Jedi Order due to its amethyst plasma blade, Windu would carry this weapon into battle on multiple occasions during the Clone Wars in which he served as a Jedi General in the Grand Army of the Republic. The lightsaber was ultimately lost during a confrontation between Windu and the Sith Lord Darth Sidious, who then killed the Jedi Order's champion through the use of Force lightning.", price: 700, image: "https://pm1.narvii.com/6214/1f2e654d21fa99e5ec4db0dec13ee89b9fe8441a_hq.jpg", status: "retired", category: category2, retired_count: 1)
item5 = Item.create!(name: "Training Lightsaber", description: "Training lightsabers were most often used by Jedi younglings before they underwent the Gathering and built a weapon of their own. It was also possible for normal lightsabers to be tuned down so they could be used in this fashion. Anakin Skywalker killed a bunch of younglings and all they had were these tiny lighsabers for self defense that's why they died.", price: 100, image: "http://www.l-ateliergourmand.com/thumbnail/r/ro-lightsabers-anakin-padawan-lightsaber-2.jpeg", category: category1, status: "active")
item6 = Item.create!(name: "Kylo Ren's Lightsaber", description: "Kylo Ren's lightsaber was a crossguard lightsaber constructed by Kylo Ren, an agent of the First Order, sometime before or during the year 34 ABY. The lightsaber, based on an ancient design dating back to the Great Scourge of Malachor, contained a cracked Kyber crystal, requiring it to have lateral vents on either side of the handle in order to divert the extra heat generated by the crystal.", price: 400, image: "https://vignette.wikia.nocookie.net/starwars/images/4/43/Kylo_lightsaber_hilt_2.png/revision/latest/scale-to-width-down/500?cb=20160607012103", category: category4, status: "active")
item7 = Item.create!(name: "Luke Skywalker's Lightsaber(Green)", description: "Luke Skywalker's green lightsaber, also known as Luke Skywalker's lightsaber was a Jedi lightsaber constructed by Jedi Knight Luke Skywalker during the Galactic Civil War. It was notably wielded during the pivotal Battle of Endor. The green-bladed weapon was powered by a kyber crystal blade stabilizing ring surrounding the blade emitter. Skywalker constructed this lightsaber shortly after he lost his father's in the duel on Cloud City.", price: 1000, image: "https://cdn.instructables.com/F21/TOEN/GYZNVV4K/F21TOENGYZNVV4K.MEDIUM.jpg", category: category2, status: "active")
item8 = Item.create!(name: "Anakin Skywalker's Lightsaber", description: "Skywalker's lightsaber was a Jedi weapon constructed by the Jedi Knight Anakin Skywalker during the Clone Wars. It was passed down to his son, Luke, and later to the scavenger Rey. Kylo Ren, the grandson of Anakin Skywalker, claimed that the lightsaber belonged to him. Obi-Wan Kenobi and Maz Kanata harbored the lightsaber, in turn, before passing it on to Luke and Rey, respectively. However, as Rey initially rejected the offer, Kanata gave the lightsaber to the renegade stormtrooper Finn, who wielded it against the First Order for a time.", price: 900, image: "https://vignette.wikia.nocookie.net/starwars/images/d/d4/Anakin_Skywalkers_first_lightsaber_-_SW_Card_Trader.png/revision/latest?cb=20160709211740", category: category1, status: "active")
item9 = Item.create!(name: "Yoda's Lightsaber", description: "What made Yoda's lightsaber unique was its scaled-down size.[1] Aside from that particularity, the weapon had a simple design, consisting of a studded chrome handle with black trim and an emitter shroud. It contained a kyber crystal that put forth a bright green plasma blade", price: 200, image: "https://i.pinimg.com/736x/d7/a6/cb/d7a6cbc78afa1b18b4aa4d7e5794ab2e--yoda-lightsaber-swords.jpg", category: category2, status: "active")
item10 = Item.create!(name: "Darth Vade's Lightsaber", description: "Darth Vader's lightsaber was the personal dual-phase lightsaber of Darth Vader, a Sith Lord who served as Darth Sidious' last apprentice and supreme military commander of the Galactic Empire. He built the weapon some time after his fall to the dark side of the Force at the end of the Clone Wars. It replaced the one he lost during his duel with Obi-Wan Kenobi on Mustafar.", price: 2000, image: "http://media.gadgetsin.com/2014/01/star_wars_darth_vader_lightsaber_backup_battery_2.jpg", category: category4, status: "active")
item11 = Item.create!(name: "Ahsoka Tano's Lightsaber", description: "In the years before the Battle of Yavin, Ahsoka Tano used two white lightsabers as her personal weapons The lightsabers, which were white in color and had somewhat curving hilts replaced the lightsabers she previously used before leaving the Jedi Order during the Clone Wars and were wielded in the unorthodox reverse-grip of her preferred Shien style. One of these lightsabers was a shoto lightsaber, which emitted a shorter blade", price: 150, image: "https://vignette2.wikia.nocookie.net/starwars/images/1/17/Ahsoka_Tano_Lightsaber_DB.png/revision/latest?cb=20160710043313", category: category1, status: "active")
item12 = Item.create!(name: "Count Dooku's Lightsaber", description: "When Dooku first set about creating this weapon, he chose a configuration that had no connection to either the weapon wielded by his first tutor, Yoda, nor to the style in fashion at the time. Studying Jedi Archive records, Dooku based his new weapon design after the curved hilts that were standard during the heyday of Form II lightsaber combat. The curve allowed the hilt to fit better into his hand, allowing for superior finesse and precise blade control", price: 400, image: "https://vignette.wikia.nocookie.net/starwars/images/8/85/DookuSaber-MR.jpg/revision/latest?cb=20071030225519", category: category3, status: "active")



order1 = Order.create(status: "Completed", total_price: 100.00, created_at: Date.today, updated_at: Date.today, user: user1)
order2 = Order.create(status: "Completed", total_price: 500.00, created_at: Date.today, updated_at: Date.today, user: user1)
order3 = Order.create(status: "Completed", total_price: 100.00, created_at: Date.today, updated_at: Date.today, user: user2)
order4 = Order.create(status: "Completed", total_price: 500.00, created_at: Date.today, updated_at: Date.today, user: user3)
order5 = Order.create(status: "Completed", total_price: 500.00, created_at: Date.today, updated_at: Date.today, user: user1)

order1.items << [item2, item2, item5]
order2.items << [item2, item3, item3]
order3.items << [item2, item5]
order4.items << [item2, item3]

puts "Seed complete!"
